// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiMiniProject.Model;
//
//    var courses = Courses.FromJson(jsonString);

namespace MauiMiniProject.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Courses
    {
        [JsonProperty("cid")]
        public long Cid { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        public static List<Courses> FromJson(string json) => JsonConvert.DeserializeObject<List<Courses>>(json, Converter.Settings);
    }
}
